name: Build

on:
  push:
    branches:
    - master
    tags:
    - release/*
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      
    - name: Configure .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
        
    - name: Build
      run: >
        dotnet build src
        --configuration Release
        -p:Branch=${{ github.ref }}
        -p:Counter=${{ github.run_number }}
