# GitHub Actions workflow
# https://help.github.com/en/actions/reference

name: Build

on:
  push:
    branches:
    - master
    tags:
    - release/*
  pull_request:
    branches:
    - '*'

env:
  # Minimize noise from dotnet CLI
  DOTNET_NOLOGO: 1

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Check Out Code
      uses: actions/checkout@v2
      
    - name: Configure .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Build
      id: build
      run: >
        dotnet build src
        --nologo
        --configuration Release
        -p:Branch=${{ github.ref }}
        -p:Counter=${{ github.run_number }}
        -p:RepositoryCommit=${{ github.sha }}

    - name: Save NuGet Package
      uses: actions/upload-artifact@v1
      with:
        name: Subatomix.Build.Versioning.Semantic ${{ steps.build.outputs.version }}
        path: dist\Subatomix.Build.Versioning.Semantic.${{ steps.build.outputs.version }}.nupkg
